//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPentruFaragau
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masina
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public string Culoare { get; set; }
        public int NumarDeRoti { get; set; }
        public int AnFabricatie { get; set; }
    }
}
